apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diary
  name: diary-service
  labels:
    app: diary-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diary-service
  template:
    metadata:
      labels:
        app: diary-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-03:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: diary-service
          image: gcr.io/fitcentive-dev-03/diary:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: "0.1"
            limits:
              memory: 800Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/diary/healthz
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/diary/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: image-service-secret
            - secretRef:
                name: diary-service-cloudsql-database-credentials
            - secretRef:
                name: diary-service-fatsecret-credentials
            - secretRef:
                name: diary-service-service-account-credentials
          env:
#            - name: JAVA_OPTS
#              value: "-Xmx128m -Xms128m"
            - name: GCP_PROJECT_NAME
              value: "fitcentive-dev-03"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
            - name: AUTH_SERVICE_HOST
              value: "http://auth-service.auth"
            - name: AUTH_SERVICE_PORT
              value: "9000"
            - name: SOCIAL_SERVICE_HOST
              value: "http://social-service.social"
            - name: SOCIAL_SERVICE_PORT
              value: "9000"
            - name: DISCOVER_SERVICE_HOST
              value: "http://discover-service.discover"
            - name: DISCOVER_SERVICE_PORT
              value: "9000"
            - name: NOTIFICATION_SERVICE_HOST
              value: "http://notification-service.notification"
            - name: NOTIFICATION_SERVICE_PORT
              value: "9000"
            - name: CHAT_SERVICE_HOST
              value: "http://chat-service.chat"
            - name: CHAT_SERVICE_PORT
              value: "4000"
            - name: IMAGE_SERVICE_HOST
              value: "http://image-service.image-service"
            - name: IMAGE_SERVICE_PORT
              value: "10260"
            - name: MEETUP_SERVICE_HOST
              value: "http://meetup-service.meetup"
            - name: MEETUP_SERVICE_PORT
              value: "9000"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service-http.keycloak/auth"
            - name: RUNTIME_ENVIRONMENT
              value: "gke-dev-env"
            - name: WGER_HOST
              value: "https://wger.de"
            - name: WGER_API_VERSION
              value: "/api/v2"
            - name: TOPIC_WARM_WGER_API_CACHE
              value: "warm-wger-api-cache"
            - name: SUBSCRIPTION_WARM_WGER_API_CACHE
              value: "warm-wger-api-cache"
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: diary-service-cloudsql-instance-credentials

