apiVersion: batch/v1
kind: CronJob
metadata:
  name: prompt-users-for-diary-entries-cron-job
  namespace: user
spec:
  # Run once a day, at 20:00 (8pm)
  schedule: "0 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prompt-users-for-diary-entries-cronjob
              image: gcr.io/fitcentive-dev-02/gcloud-diary-entry-prompt-cron-pubsub-image:1.0
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /opt/service-account
                  name: service-account
          restartPolicy: OnFailure
          volumes:
            - name: service-account
              configMap:
                name: diary-service-service-account